server:
  port: 8080


management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: "*"
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true


udps :
  serverConfigFilePath : classpath:server-config.json
  sim.delay : 200
  #serverConfigFilePath : /server-config.json

logging:
  level:
    open.vm.socket : INFO
#  path: ./
#  file: tcp-cluster.log



