{
 "title": "Socker Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "TCP Server",
    "query": "label_values(udm_tcp_connections, name)\t"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "targets": [
    { "expr": "udm_tcp_connections" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 5, "x": 17, "y": 0 } },
  {
   "title": "Client Connection Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(udm_tcp_connection_requests_seconds_count{name=~\"$name\"}[1m])"
    }
   ]
  },
  {
   "title": "Client Connections per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(udm_tcp_connection_requests_seconds_count{name=~\"$name\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}