global:
  scrape_interval: 1m
  scrape_timeout: 5s
  evaluation_interval: 1m
scrape_configs:
  - job_name: 'socket-cluster'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    basic_auth:
      username: 'admin'
      password: 'password'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'hystrix-demo'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    basic_auth:
      username: 'admin'
      password: 'password'
    static_configs:
      - targets: ['host.docker.internal:8088']

